import { Fragment, useEffect, useState } from "react";
import { useStableCallback } from "../hooks/useStableCallback";
import { CheckCircle2, Link2, Landmark, Plus, RefreshCw, Trash2, Unlink, Upload } from "lucide-react";
import toast from "react-hot-toast";

import JalaliDateField from "../components/forms/JalaliDateField";
import { useLanguage } from "../localization/useLanguage";
import { toPersianDigits, toEnglishDigits, cleanNumberInput } from "../localization/helpers";
import { addBankStatementLine, createBankAccount, deleteBankStatementLine, getBankAccounts, getBankCandidates, getBankReconciliationSummary, getBankStatement, importBankStatementCsv, matchBankStatementLine, unmatchBankStatementLine } from "../services/bankReconciliationApi";
import Select from "../components/ui/Select";

export default function BankReconciliation() {
  const { language, dir, money, date, n } = useLanguage();
  const [accounts,setAccounts]=useState([]), [accountId,setAccountId]=useState("");
  const [lines,setLines]=useState([]), [summary,setSummary]=useState(null), [candidates,setCandidates]=useState({});
  const [loading,setLoading]=useState(true), [error,setError]=useState("");
  const [accountForm,setAccountForm]=useState({name:"",bank_name:"",account_number:"",iban:"",ledger_account_code:language==="fa"?toPersianDigits("1102"):"1102",opening_balance:0});
  const [lineForm,setLineForm]=useState({transaction_date:new Date().toISOString().slice(0,10),description:"",reference:"",amount:""});
  const copy={
    title:language==="fa"?"مغایرت‌گیری بانکی":language==="ar"?"التسوية البنكية":language==="tr"?"Banka Mutabakatı":"Bank Reconciliation", subtitle:language==="fa"?"تطبیق صورتحساب بانک با اسناد قطعی دفتر کل":language==="ar"?"مطابقة كشف الحساب البنكي مع القيود المرحّلة في دفتر الأستاذ العام":language==="tr"?"Banka hesap özetini kesinleşmiş büyük defter kayıtlarıyla eşleştirin":"Match bank statements against posted general-ledger entries",
    account:language==="fa"?"حساب بانکی":language==="ar"?"الحساب البنكي":language==="tr"?"Banka Hesabı":"Bank account",newAccount:language==="fa"?"تعریف حساب":language==="ar"?"إضافة حساب":language==="tr"?"Hesap Ekle":"Add account",bank:language==="fa"?"نام بانک":language==="ar"?"البنك":language==="tr"?"Banka":"Bank",number:language==="fa"?"شماره حساب":language==="ar"?"رقم الحساب":language==="tr"?"Hesap Numarası":"Account number",opening:language==="fa"?"مانده ابتدای صورتحساب":language==="ar"?"الرصيد الافتتاحي لكشف الحساب":language==="tr"?"Ekstre Açılış Bakiyesi":"Statement opening",save:language==="fa"?"ذخیره":language==="ar"?"حفظ":language==="tr"?"Kaydet":"Save",
    iban:language==="fa"?"شماره شبا":language==="ar"?"رقم الآيبان":language==="tr"?"IBAN":"IBAN",ledgerCode:language==="fa"?"کد حساب دفتر کل":language==="ar"?"رمز حساب الأستاذ العام":language==="tr"?"Büyük Defter Hesap Kodu":"GL account code",
    addLine:language==="fa"?"افزودن گردش صورتحساب":language==="ar"?"إضافة حركة كشف حساب":language==="tr"?"Ekstre Satırı Ekle":"Add statement line",date:language==="fa"?"تاریخ":language==="ar"?"التاريخ":language==="tr"?"Tarih":"Date",description:language==="fa"?"شرح":language==="ar"?"الوصف":language==="tr"?"Açıklama":"Description",reference:language==="fa"?"مرجع":language==="ar"?"المرجع":language==="tr"?"Referans":"Reference",amount:language==="fa"?"مبلغ (+واریز / -برداشت)":language==="ar"?"المبلغ (+إيداع / -سحب)":language==="tr"?"Tutar (+giriş / -çıkış)":"Amount (+in / -out)",
    statement:language==="fa"?"صورتحساب":language==="ar"?"كشف الحساب":language==="tr"?"Ekstre":"Statement",ledger:language==="fa"?"دفتر کل":language==="ar"?"دفتر الأستاذ":language==="tr"?"Büyük Defter":"Ledger",matched:language==="fa"?"تطبیق‌شده":language==="ar"?"مطابَق":language==="tr"?"Eşleşti":"Matched",unmatched:language==="fa"?"تطبیق‌نشده":language==="ar"?"غير مطابَق":language==="tr"?"Eşleşmedi":"Unmatched",difference:language==="fa"?"اختلاف":language==="ar"?"الفرق":language==="tr"?"Fark":"Difference",reconciled:language==="fa"?"تطبیق کامل":language==="ar"?"مسوّى بالكامل":language==="tr"?"Tamamen Mutabık":"Reconciled",
    find:language==="fa"?"یافتن سند":language==="ar"?"البحث عن قيد":language==="tr"?"Kayıt Bul":"Find ledger entry",unmatch:language==="fa"?"لغو تطبیق":language==="ar"?"إلغاء المطابقة":language==="tr"?"Eşleşmeyi Kaldır":"Unmatch",delete:language==="fa"?"حذف":language==="ar"?"حذف":language==="tr"?"Sil":"Delete",voucher:language==="fa"?"سند":language==="ar"?"السند":language==="tr"?"Fiş":"Voucher",noData:language==="fa"?"گردشی ثبت نشده است.":language==="ar"?"لا توجد حركات مسجّلة بعد.":language==="tr"?"Henüz ekstre satırı yok.":"No statement lines yet.",refresh:language==="fa"?"به‌روزرسانی":language==="ar"?"تحديث":language==="tr"?"Yenile":"Refresh",
    importCsv:language==="fa"?"وارد کردن فایل CSV":language==="ar"?"استيراد ملف CSV":language==="tr"?"CSV Dosyası İçe Aktar":"Import CSV file",
    importHint:language==="fa"?"ستون‌های مورد انتظار: date، description، reference، amount (یا deposit/withdrawal)":language==="ar"?"الأعمدة المتوقعة: date، description، reference، amount (أو deposit/withdrawal)":language==="tr"?"Beklenen sütunlar: date, description, reference, amount (veya deposit/withdrawal)":"Expected columns: date, description, reference, amount (or deposit/withdrawal)",
    importResult:(imported,skipped)=>language==="fa"?`${n(imported)} ردیف وارد شد، ${n(skipped)} ردیف رد شد.`:language==="ar"?`تم استيراد ${n(imported)} سطرًا، وتم تخطي ${n(skipped)}.`:language==="tr"?`${n(imported)} satır içe aktarıldı, ${n(skipped)} satır atlandı.`:`${imported} rows imported, ${skipped} skipped.`,
  };
  async function load(id=accountId){
    setLoading(true);setError("");
    try{
      const list=await getBankAccounts();setAccounts(list);
      const selected=id||list[0]?.id||"";setAccountId(String(selected));
      if(selected){const [statement,totals]=await Promise.all([getBankStatement(selected),getBankReconciliationSummary(selected)]);setLines(statement);setSummary(totals);}
      else{setLines([]);setSummary(null);}
    }catch(e){setError(e.message);}finally{setLoading(false);}
  }
  const stableLoad = useStableCallback(load);

  useEffect(()=>{const initialTimer = setTimeout(() => { void stableLoad(""); }, 0);return()=>clearTimeout(initialTimer);},[language, stableLoad]);
  async function submitAccount(e){e.preventDefault();try{const payload={...accountForm,account_number:toEnglishDigits(accountForm.account_number),ledger_account_code:toEnglishDigits(accountForm.ledger_account_code)};const r=await createBankAccount(payload);setAccountForm({...accountForm,name:"",bank_name:"",account_number:"",iban:""});await load(r.id);toast.success(copy.save);}catch(e){toast.error(e.message);}}
  async function submitLine(e){e.preventDefault();if(!accountId)return;try{await addBankStatementLine(accountId,{...lineForm,amount:Number(lineForm.amount)});setLineForm({...lineForm,description:"",reference:"",amount:""});await load(accountId);}catch(e){toast.error(e.message);}}
  async function handleImportCsv(e){const file=e.target.files?.[0];e.target.value="";if(!file||!accountId)return;try{const result=await importBankStatementCsv(accountId,file);toast.success(copy.importResult(result.imported,result.skipped));if(result.errors?.length)console.warn("Bank statement import issues:",result.errors);await load(accountId);}catch(err){toast.error(err.message);}}
  async function find(line){try{setCandidates({...candidates,[line.id]:await getBankCandidates(accountId,line.id)});}catch(e){toast.error(e.message);}}
  async function match(lineId,voucherLineId){try{await matchBankStatementLine(lineId,voucherLineId);setCandidates({...candidates,[lineId]:[]});await load(accountId);}catch(e){toast.error(e.message);}}
  async function unmatch(id){try{await unmatchBankStatementLine(id);await load(accountId);}catch(e){toast.error(e.message);}}
  async function remove(id){try{await deleteBankStatementLine(id);await load(accountId);}catch(e){toast.error(e.message);}}
  const card={background:"var(--erp-panel)",border:"1px solid var(--erp-border)",borderRadius:22,boxShadow:"0 18px 55px rgba(2,6,23,.3)"};
  const input={background:"var(--erp-panel-solid)",color:"var(--erp-text)",border:"1px solid var(--erp-border)",borderRadius:11,padding:"10px 12px",minWidth:0};
  const button={border:0,borderRadius:11,padding:"10px 13px",fontWeight:900,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:6};
  return <div dir={dir} style={{color:"var(--erp-text)",maxWidth:1500,margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap",alignItems:"center",marginBottom:20}}><div style={{display:"flex",gap:13,alignItems:"center"}}><div style={{width:55,height:55,borderRadius:17,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#06b6d4,#2563eb)"}}><Landmark size={30}/></div><div><h1 style={{margin:0,color:"var(--erp-accent)",fontSize:"clamp(28px,4vw,40px)"}}>{copy.title}</h1><p style={{margin:"6px 0 0",color:"var(--erp-muted)"}}>{copy.subtitle}</p></div></div><button onClick={()=>load()} style={{...button,background:"var(--erp-panel-solid)",color:"var(--erp-accent)"}}><RefreshCw size={16}/>{loading?"...":copy.refresh}</button></header>
    {error&&<div className="text-red-200" style={{...card,padding:15,marginBottom:15}}>{error}</div>}
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14,marginBottom:15}}>
      <form onSubmit={submitAccount} style={{...card,padding:17}}><h3 style={{marginTop:0,color:"var(--erp-accent)"}}>{copy.newAccount}</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input required placeholder={copy.account} value={accountForm.name} onChange={e=>setAccountForm({...accountForm,name:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input placeholder={copy.bank} value={accountForm.bank_name} onChange={e=>setAccountForm({...accountForm,bank_name:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input placeholder={copy.number} value={language==="fa"?toPersianDigits(accountForm.account_number):accountForm.account_number} onChange={e=>setAccountForm({...accountForm,account_number:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input placeholder={copy.iban} value={accountForm.iban} onChange={e=>setAccountForm({...accountForm,iban:e.target.value})} style={{...input,direction:"ltr"}}/><input placeholder={copy.ledgerCode} value={language==="fa"?toPersianDigits(accountForm.ledger_account_code):accountForm.ledger_account_code} onChange={e=>setAccountForm({...accountForm,ledger_account_code:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input type="text" inputMode="numeric" placeholder={copy.opening} value={language === "fa" ? toPersianDigits(accountForm.opening_balance) : accountForm.opening_balance} onChange={e=>setAccountForm({...accountForm,opening_balance:Number(cleanNumberInput(e.target.value)) || 0})} style={input}/></div><button style={{...button,background:"var(--erp-success-solid)",color:"var(--erp-success-solid-text)",marginTop:9}}><Plus size={16}/>{copy.save}</button></form>
      <form onSubmit={submitLine} style={{...card,padding:17}}><h3 className="text-violet-300" style={{marginTop:0}}>{copy.addLine}</h3><Select value={accountId} onChange={(value)=>load(value)} className="w-full mb-2" options={[{value:"",label:copy.account},...accounts.map(a=>({value:a.id,label:`${a.name} — ${a.bank_name}`}))]}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><JalaliDateField value={lineForm.transaction_date} onChange={(iso)=>setLineForm({...lineForm,transaction_date:iso})} fa={language === "fa"} language={language} className="bg-[var(--erp-panel-solid)] text-[var(--erp-text)] border border-[var(--erp-border)] rounded-[11px] p-[10px_12px]"/><input required type="text" inputMode="numeric" placeholder={copy.amount} value={language === "fa" ? toPersianDigits(lineForm.amount) : lineForm.amount} onChange={e=>setLineForm({...lineForm,amount:cleanNumberInput(e.target.value)})} style={input}/><input placeholder={copy.description} value={lineForm.description} onChange={e=>setLineForm({...lineForm,description:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input placeholder={copy.reference} value={lineForm.reference} onChange={e=>setLineForm({...lineForm,reference:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/></div><button disabled={!accountId} style={{...button,background:"#6d28d9",color:"#ede9fe",marginTop:9}}><Plus size={16}/>{copy.addLine}</button>
        <div style={{marginTop:14,paddingTop:14,borderTop:"1px solid var(--erp-border)"}}>
          <label style={{...button,background:"var(--erp-panel-solid)",color:"var(--erp-accent)",opacity:accountId?1:.5,cursor:accountId?"pointer":"not-allowed"}}>
            <Upload size={16}/>{copy.importCsv}
            <input type="file" accept=".csv,text/csv" disabled={!accountId} onChange={handleImportCsv} style={{display:"none"}}/>
          </label>
          <div style={{color:"var(--erp-muted)",fontSize:12,marginTop:6}}>{copy.importHint}</div>
        </div>
      </form>
    </section>
    {summary&&<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10,marginBottom:15}}>{[[copy.statement,summary.statement.amount,"var(--erp-accent)"],[copy.ledger,summary.ledger.amount,null,"text-violet-300"],[copy.matched,summary.statement.matched_count,null,"text-green-300"],[copy.unmatched,summary.statement.unmatched_count,"#fbbf24"],[copy.difference,summary.difference,summary.reconciled?"#86efac":"#fda4af"]].map(([label,value,color,cls],i)=><div key={label} style={{...card,padding:15}}><div style={{color:"var(--erp-muted)"}}>{label}</div><strong className={cls} style={{display:"block",fontSize:20,marginTop:6,...(cls?null:{color})}}>{i===2||i===3?n(value):money(value)}</strong></div>)}</section>}
    <section style={{...card,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:850}}><thead><tr><th style={{padding:12,textAlign:"start",color:"var(--erp-accent)"}}>#</th>{[copy.date,copy.description,copy.reference,copy.amount,copy.matched,""].map(x=><th key={x} style={{padding:12,textAlign:"start",color:"var(--erp-accent)"}}>{x}</th>)}</tr></thead><tbody>{!lines.length&&<tr><td colSpan={7} style={{padding:24,textAlign:"center",color:"var(--erp-muted)"}}>{copy.noData}</td></tr>}{lines.map((line,rowIndex)=><Fragment key={line.id}><tr><td style={{padding:12,borderTop:"1px solid var(--erp-border)",color:"var(--erp-muted)",fontWeight:700}}>{n(rowIndex+1)}</td>{[date(line.transaction_date),line.description||"—",line.reference||"—"].map((v,i)=><td key={i} style={{padding:12,borderTop:"1px solid var(--erp-border)"}}>{v}</td>)}<td style={{padding:12,color:line.amount>=0?"#86efac":"#fda4af",fontWeight:900}}>{money(line.amount)}</td><td style={{padding:12,color:line.matched?"#86efac":"#fbbf24"}}>{line.matched?<><CheckCircle2 size={16}/> {n(line.voucher_no)}</>:copy.unmatched}</td><td style={{padding:12,whiteSpace:"nowrap"}}>{line.matched?<button onClick={()=>unmatch(line.id)} style={{...button,background:"var(--erp-warning-solid)",color:"var(--erp-warning-solid-text)"}}><Unlink size={15}/>{copy.unmatch}</button>:<button onClick={()=>find(line)} style={{...button,background:"var(--erp-panel-solid)",color:"var(--erp-accent)"}}><Link2 size={15}/>{copy.find}</button>} <button onClick={()=>remove(line.id)} style={{...button,background:"var(--erp-danger-solid)",color:"var(--erp-danger-solid-text)"}}><Trash2 size={15}/></button></td></tr>{candidates[line.id]?.length>0&&<tr key={line.id+"-matches"}><td colSpan={7} style={{padding:12,background:"var(--erp-glow)"}}>{candidates[line.id].slice(0,8).map(c=><button key={c.voucher_line_id} onClick={()=>match(line.id,c.voucher_line_id)} disabled={!c.exact_amount} style={{...button,margin:4,background:c.exact_amount?"var(--erp-success-solid)":"var(--erp-panel-solid)",color:c.exact_amount?"white":"var(--erp-muted)",opacity:c.exact_amount?1:.55}}>{copy.voucher} {n(c.voucher_no)} — {date(c.voucher_date)} — {money(c.amount)}</button>)}</td></tr>}</Fragment>)}</tbody></table></section>
  </div>;
}
