import { useEffect,useState } from "react";
import { useStableCallback } from "../hooks/useStableCallback";
import { AlertTriangle,BriefcaseBusiness,Building2,Plus,RefreshCw,Target,Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import { useLanguage } from "../localization/useLanguage";
import { toPersianDigits, cleanNumberInput } from "../localization/helpers";
import { getAccountingChart } from "../services/accountingApi";
import { getFiscalPeriods } from "../services/fiscalPeriodsApi";
import { createAccountingProject,createCostCenter,deleteBudgetLine,getBudgetDimensions,getBudgetVariance,saveBudgetLine } from "../services/budgetApi";

export default function BudgetControl(){
 const {language,dir,money,n}=useLanguage();
 const [periods,setPeriods]=useState([]),[periodId,setPeriodId]=useState(""),[dims,setDims]=useState({cost_centers:[],projects:[]}),[accounts,setAccounts]=useState([]),[data,setData]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const [centerFilter,setCenterFilter]=useState(""),[projectFilter,setProjectFilter]=useState("");
 const [dimension,setDimension]=useState({type:"center",code:"",name:""});
 const [budget,setBudget]=useState({account_id:"",cost_center_id:"",project_id:"",amount:"",note:""});
 const c={title:language==="fa"?"بودجه و مراکز هزینه":language==="ar"?"الموازنة ومراكز التكلفة":language==="tr"?"Bütçe ve Maliyet Merkezleri":"Budget & Cost Control",sub:language==="fa"?"کنترل بودجه دوره‌ای، پروژه‌ها و انحراف عملکرد واقعی دفترکل":language==="ar"?"مراقبة موازنة الفترة، المشاريع، مراكز التكلفة، وانحراف الأداء الفعلي عن دفتر الأستاذ":language==="tr"?"Dönemsel bütçe, projeler, maliyet merkezleri ve büyük defter gerçekleşme sapması":"Period budgets, projects, cost centers, and actual-ledger variance",period:language==="fa"?"دوره مالی":language==="ar"?"الفترة المالية":language==="tr"?"Mali Dönem":"Fiscal period",all:language==="fa"?"همه ابعاد":language==="ar"?"جميع الأبعاد":language==="tr"?"Tüm Boyutlar":"All dimensions",center:language==="fa"?"مرکز هزینه":language==="ar"?"مركز التكلفة":language==="tr"?"Maliyet Merkezi":"Cost center",project:language==="fa"?"پروژه":language==="ar"?"المشروع":language==="tr"?"Proje":"Project",code:language==="fa"?"کد":language==="ar"?"الرمز":language==="tr"?"Kod":"Code",name:language==="fa"?"نام":language==="ar"?"الاسم":language==="tr"?"Ad":"Name",add:language==="fa"?"افزودن":language==="ar"?"إضافة":language==="tr"?"Ekle":"Add",budget:language==="fa"?"ثبت بودجه":language==="ar"?"تحديد الموازنة":language==="tr"?"Bütçe Belirle":"Set budget",account:language==="fa"?"حساب درآمد/هزینه":language==="ar"?"حساب الإيرادات/المصروفات":language==="tr"?"Gelir/Gider Hesabı":"Revenue/expense account",amount:language==="fa"?"مبلغ بودجه":language==="ar"?"مبلغ الموازنة":language==="tr"?"Bütçe Tutarı":"Budget amount",note:language==="fa"?"یادداشت":language==="ar"?"ملاحظة":language==="tr"?"Not":"Note",refresh:language==="fa"?"به‌روزرسانی":language==="ar"?"تحديث":language==="tr"?"Yenile":"Refresh",totalBudget:language==="fa"?"کل بودجه":language==="ar"?"إجمالي الموازنة":language==="tr"?"Toplam Bütçe":"Total budget",actual:language==="fa"?"عملکرد واقعی":language==="ar"?"الفعلي":language==="tr"?"Gerçekleşen":"Actual",variance:language==="fa"?"انحراف":language==="ar"?"الانحراف":language==="tr"?"Sapma":"Variance",usage:language==="fa"?"درصد مصرف":language==="ar"?"نسبة الاستخدام":language==="tr"?"Kullanım Oranı":"Usage",over:language==="fa"?"ردیف‌های بیش از بودجه":language==="ar"?"بنود تجاوزت الموازنة":language==="tr"?"Bütçe Aşan Kalemler":"Over-budget lines",no:language==="fa"?"بودجه‌ای برای این فیلتر ثبت نشده است.":language==="ar"?"لا توجد بنود موازنة لهذا التحديد.":language==="tr"?"Bu seçim için bütçe kalemi yok.":"No budget lines for this selection.",delete:language==="fa"?"حذف":language==="ar"?"حذف":language==="tr"?"Sil":"Delete"};
 async function bootstrap(){setLoading(true);setError("");try{const [p,d,a]=await Promise.all([getFiscalPeriods(),getBudgetDimensions(),getAccountingChart()]);setPeriods(p);setDims(d);setAccounts(a.filter(x=>["revenue","expense","contra"].includes(x.account_type)));const pid=periodId||p[0]?.id||"";setPeriodId(String(pid));if(pid)setData(await getBudgetVariance(pid,centerFilter,projectFilter))}catch(e){setError(e.message)}finally{setLoading(false)}}
 const stableBootstrap = useStableCallback(bootstrap);

 useEffect(()=>{
  const timer = setTimeout(() => { void stableBootstrap(); }, 0);
  return () => clearTimeout(timer);
 },[language, stableBootstrap]);
 async function load(){if(!periodId)return;setLoading(true);try{setData(await getBudgetVariance(periodId,centerFilter,projectFilter));setDims(await getBudgetDimensions())}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function addDimension(e){e.preventDefault();try{const fn=dimension.type==="center"?createCostCenter:createAccountingProject;await fn({code:dimension.code,name:dimension.name});setDimension({...dimension,code:"",name:""});await load()}catch(e){toast.error(e.message)}}
 async function addBudget(e){e.preventDefault();try{await saveBudgetLine({fiscal_period_id:Number(periodId),account_id:Number(budget.account_id),cost_center_id:budget.cost_center_id?Number(budget.cost_center_id):null,project_id:budget.project_id?Number(budget.project_id):null,amount:Number(budget.amount),note:budget.note});setBudget({...budget,amount:"",note:""});await load()}catch(e){toast.error(e.message)}}
 async function remove(id){try{await deleteBudgetLine(id);await load()}catch(e){toast.error(e.message)}}
 const card={background:"var(--erp-panel)",border:"1px solid var(--erp-border)",borderRadius:22,boxShadow:"0 18px 55px rgba(2,6,23,.3)"},input={background:"var(--erp-panel-solid)",color:"var(--erp-text)",border:"1px solid var(--erp-border)",borderRadius:11,padding:"10px 12px",minWidth:0},button={border:0,borderRadius:11,padding:"10px 13px",fontWeight:900,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:6};
 return <div dir={dir} style={{color:"var(--erp-text)",maxWidth:1500,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap",alignItems:"center",marginBottom:20}}><div style={{display:"flex",gap:13,alignItems:"center"}}><div style={{width:55,height:55,borderRadius:17,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#22c55e,#06b6d4)"}}><Target size={30}/></div><div><h1 className="text-green-300" style={{margin:0,fontSize:"clamp(28px,4vw,40px)"}}>{c.title}</h1><p style={{margin:"6px 0 0",color:"var(--erp-muted)"}}>{c.sub}</p></div></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><select value={periodId} onChange={e=>setPeriodId(e.target.value)} style={input}>{periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={centerFilter} onChange={e=>setCenterFilter(e.target.value)} style={input}><option value="">{c.all}</option>{dims.cost_centers.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><select value={projectFilter} onChange={e=>setProjectFilter(e.target.value)} style={input}><option value="">{c.all}</option>{dims.projects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><button onClick={load} style={{...button,background:"var(--erp-panel-solid)",color:"var(--erp-accent)"}}><RefreshCw size={16}/>{loading?"...":c.refresh}</button></div></header>
  {error&&<div className="text-red-200" style={{...card,padding:15,marginBottom:15}}>{error}</div>}
  {data&&<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(175px,1fr))",gap:10,marginBottom:15}}>{[[c.totalBudget,money(data.summary.budget),null,"text-violet-300"],[c.actual,money(data.summary.actual),"var(--erp-accent)"],[c.variance,money(data.summary.variance),data.summary.variance<0?"#fda4af":"#86efac"],[c.usage,n(data.summary.usage_percent)+"%","#fbbf24"],[c.over,n(data.summary.over_budget_count),"#fda4af"]].map(([l,v,color,cls])=><div key={l} style={{...card,padding:16}}><div style={{color:"var(--erp-muted)"}}>{l}</div><strong className={cls} style={{display:"block",fontSize:21,marginTop:6,...(cls?null:{color})}}>{v}</strong></div>)}</section>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))",gap:14,marginBottom:15}}>
   <form onSubmit={addDimension} style={{...card,padding:17}}><h3 style={{marginTop:0,color:"var(--erp-accent)"}}><Building2 size={18} style={{display:"inline",marginInlineEnd:7}}/>{dimension.type==="center"?c.center:c.project}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8}}><select value={dimension.type} onChange={e=>setDimension({...dimension,type:e.target.value})} style={input}><option value="center">{c.center}</option><option value="project">{c.project}</option></select><input required placeholder={c.code} value={dimension.code} onChange={e=>setDimension({...dimension,code:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input required placeholder={c.name} value={dimension.name} onChange={e=>setDimension({...dimension,name:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/></div><button style={{...button,background:"#166534",color:"#dcfce7",marginTop:9}}><Plus size={16}/>{c.add}</button></form>
   <form onSubmit={addBudget} style={{...card,padding:17}}><h3 className="text-violet-300" style={{marginTop:0}}><BriefcaseBusiness size={18} style={{display:"inline",marginInlineEnd:7}}/>{c.budget}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8}}><select required value={budget.account_id} onChange={e=>setBudget({...budget,account_id:e.target.value})} style={input}><option value="">{c.account}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select><input required type="text" inputMode="numeric" placeholder={c.amount} value={language === "fa" ? toPersianDigits(budget.amount) : budget.amount} onChange={e=>setBudget({...budget,amount:cleanNumberInput(e.target.value)})} style={input}/><select value={budget.cost_center_id} onChange={e=>setBudget({...budget,cost_center_id:e.target.value})} style={input}><option value="">{c.center}</option>{dims.cost_centers.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><select value={budget.project_id} onChange={e=>setBudget({...budget,project_id:e.target.value})} style={input}><option value="">{c.project}</option>{dims.projects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div><button disabled={!periodId} style={{...button,background:"#6d28d9",color:"#ede9fe",marginTop:9}}><Plus size={16}/>{c.budget}</button></form>
  </section>
  <section style={{...card,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr>{[c.account,c.center,c.project,c.totalBudget,c.actual,c.variance,c.usage,""].map(x=><th key={x} style={{padding:12,textAlign:"start",color:"var(--erp-accent)"}}>{x}</th>)}</tr></thead><tbody>{!data?.items.length&&<tr><td colSpan={8} style={{padding:25,textAlign:"center",color:"var(--erp-muted)"}}>{c.no}</td></tr>}{data?.items.map(x=><tr key={x.budget_id}><td style={{padding:12,borderTop:"1px solid var(--erp-border)",fontWeight:900}}>{x.account_code} — {x.account_name}</td><td style={{padding:12}}>{x.cost_center_name||"—"}</td><td style={{padding:12}}>{x.project_name||"—"}</td><td style={{padding:12}}>{money(x.budget_amount)}</td><td style={{padding:12}}>{money(x.actual_amount)}</td><td style={{padding:12,color:x.over_budget?"#fda4af":"#86efac",fontWeight:900}}>{x.over_budget&&<AlertTriangle size={15} style={{display:"inline"}}/>} {money(x.variance)}</td><td style={{padding:12,color:x.over_budget?"#fbbf24":"inherit"}}>{n(x.usage_percent)}%</td><td style={{padding:12}}><button onClick={()=>remove(x.budget_id)} style={{...button,background:"#7f1d1d",color:"#fee2e2"}}><Trash2 size={15}/></button></td></tr>)}</tbody></table></section>
 </div>
}
