import { useEffect,useState } from "react";
import { useStableCallback } from "../hooks/useStableCallback";
import { Coins,Plus,RefreshCw,TrendingUp } from "lucide-react";
import toast from "react-hot-toast";
import JalaliDateField from "../components/forms/JalaliDateField";
import { useLanguage } from "../localization/useLanguage";
import { toPersianDigits, cleanNumberInput } from "../localization/helpers";
import { getFiscalPeriods } from "../services/fiscalPeriodsApi";
import { createCurrency,getCurrencies,getForeignCurrencyBalances,setExchangeRate } from "../services/currencyApi";

export default function CurrencyManagement(){
 const {language,dir,money,date,n}=useLanguage();
 const today=new Date().toISOString().slice(0,10);
 const [currencies,setCurrencies]=useState([]),[periods,setPeriods]=useState([]),[periodId,setPeriodId]=useState(""),[asOf,setAsOf]=useState(today),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [currency,setCurrency]=useState({code:"",name:"",symbol:""}),[rate,setRate]=useState({currency_code:"",rate_date:today,rate_to_base:""});
 const c={title:language==="fa"?"حسابداری چندارزی":language==="ar"?"محاسبة متعددة العملات":language==="tr"?"Çoklu Döviz Muhasebesi":"Multi-Currency Accounting",sub:language==="fa"?"مدیریت ارز، تاریخچه نرخ و ارزش‌گذاری مانده‌های ارزی دفترکل":language==="ar"?"سجل العملات، أسعار الصرف، وإعادة تقييم أرصدة دفتر الأستاذ بالعملات الأجنبية":language==="tr"?"Döviz kayıtları, kur geçmişi ve büyük defter döviz bakiyelerinin yeniden değerlemesi":"Currency registry, exchange rates, and ledger balance revaluation",addCurrency:language==="fa"?"تعریف ارز":language==="ar"?"إضافة عملة":language==="tr"?"Döviz Ekle":"Add currency",code:language==="fa"?"کد سه‌حرفی":language==="ar"?"الرمز المكوّن من 3 أحرف":language==="tr"?"3 Harfli Kod":"3-letter code",name:language==="fa"?"نام ارز":language==="ar"?"اسم العملة":language==="tr"?"Döviz Adı":"Currency name",symbol:language==="fa"?"نماد":language==="ar"?"الرمز":language==="tr"?"Sembol":"Symbol",save:language==="fa"?"ذخیره":language==="ar"?"حفظ":language==="tr"?"Kaydet":"Save",setRate:language==="fa"?"ثبت نرخ":language==="ar"?"تحديد سعر الصرف":language==="tr"?"Kur Belirle":"Set exchange rate",currency:language==="fa"?"ارز":language==="ar"?"العملة":language==="tr"?"Döviz":"Currency",rate:language==="fa"?"نرخ به ارز پایه":language==="ar"?"السعر مقابل العملة الأساسية":language==="tr"?"Ana Para Birimine Kur":"Rate to base",rateDate:language==="fa"?"تاریخ نرخ":language==="ar"?"تاريخ السعر":language==="tr"?"Kur Tarihi":"Rate date",period:language==="fa"?"دوره مالی":language==="ar"?"الفترة المالية":language==="tr"?"Mali Dönem":"Fiscal period",all:language==="fa"?"همه دوره‌ها":language==="ar"?"جميع الفترات":language==="tr"?"Tüm Dönemler":"All periods",asOf:language==="fa"?"ارزش‌گذاری تا تاریخ":language==="ar"?"إعادة التقييم حتى تاريخ":language==="tr"?"Değerleme Tarihi":"Revalue as of",refresh:language==="fa"?"به‌روزرسانی":language==="ar"?"تحديث":language==="tr"?"Yenile":"Refresh",carrying:language==="fa"?"ارزش دفتری":language==="ar"?"القيمة الدفترية":language==="tr"?"Defter Değeri":"Carrying value",current:language==="fa"?"ارزش روز":language==="ar"?"القيمة الحالية":language==="tr"?"Güncel Değer":"Current value",difference:language==="fa"?"تفاوت تسعیر":language==="ar"?"فرق التقييم غير المحقق":language==="tr"?"Gerçekleşmemiş Kur Farkı":"Unrealized difference",foreign:language==="fa"?"مانده ارزی":language==="ar"?"الرصيد بالعملة الأجنبية":language==="tr"?"Döviz Bakiyesi":"Foreign balance",account:language==="fa"?"حساب":language==="ar"?"الحساب":language==="tr"?"Hesap":"Account",latest:language==="fa"?"آخرین نرخ":language==="ar"?"آخر سعر":language==="tr"?"Son Kur":"Latest rate",no:language==="fa"?"مانده ارزی ثبت‌شده‌ای وجود ندارد.":language==="ar"?"لا توجد أرصدة بعملات أجنبية.":language==="tr"?"Döviz bakiyesi bulunmuyor.":"No foreign-currency balances.",total:language==="fa"?"جمع تفاوت تسعیر":language==="ar"?"إجمالي فرق التقييم غير المحقق":language==="tr"?"Toplam Gerçekleşmemiş Kur Farkı":"Total unrealized difference"};
 async function load(){setLoading(true);setError("");try{const [cs,ps,b]=await Promise.all([getCurrencies(asOf),getFiscalPeriods(),getForeignCurrencyBalances(periodId,asOf)]);setCurrencies(cs);setPeriods(ps);setData(b);if(!rate.currency_code&&cs.find(x=>!x.is_base))setRate(r=>({...r,currency_code:cs.find(x=>!x.is_base).code}))}catch(e){setError(e.message)}finally{setLoading(false)}}
 const stableLoad = useStableCallback(load);

 useEffect(()=>{
  const timer = setTimeout(() => { void stableLoad(); }, 0);
  return () => clearTimeout(timer);
 },[language, stableLoad]);
 async function addCurrency(e){e.preventDefault();try{await createCurrency(currency);setCurrency({code:"",name:"",symbol:""});await load()}catch(e){toast.error(e.message)}}
 async function addRate(e){e.preventDefault();try{await setExchangeRate({...rate,rate_to_base:Number(rate.rate_to_base)});setRate({...rate,rate_to_base:""});await load()}catch(e){toast.error(e.message)}}
 const card={background:"var(--erp-panel)",border:"1px solid var(--erp-border)",borderRadius:22,boxShadow:"0 18px 55px rgba(2,6,23,.3)"},input={background:"var(--erp-panel-solid)",color:"var(--erp-text)",border:"1px solid var(--erp-border)",borderRadius:11,padding:"10px 12px",minWidth:0},button={border:0,borderRadius:11,padding:"10px 13px",fontWeight:900,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:6};
 return <div dir={dir} style={{color:"var(--erp-text)",maxWidth:1500,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap",alignItems:"center",marginBottom:20}}><div style={{display:"flex",gap:13,alignItems:"center"}}><div style={{width:55,height:55,borderRadius:17,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#f59e0b,#22c55e)"}}><Coins size={30}/></div><div><h1 style={{margin:0,color:"#fde68a",fontSize:"clamp(28px,4vw,40px)"}}>{c.title}</h1><p style={{margin:"6px 0 0",color:"var(--erp-muted)"}}>{c.sub}</p></div></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><select value={periodId} onChange={e=>setPeriodId(e.target.value)} style={input}><option value="">{c.all}</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><JalaliDateField value={asOf} onChange={setAsOf} fa={language === "fa"} language={language} className="bg-[var(--erp-panel-solid)] text-[var(--erp-text)] border border-[var(--erp-border)] rounded-[11px] p-[10px_12px]"/><button onClick={load} style={{...button,background:"var(--erp-panel-solid)",color:"var(--erp-accent)"}}><RefreshCw size={16}/>{loading?"...":c.refresh}</button></div></header>
  {error&&<div style={{...card,padding:15,color:"#fecaca",marginBottom:15}}>{error}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14,marginBottom:15}}>
   <form onSubmit={addCurrency} style={{...card,padding:17}}><h3 style={{marginTop:0,color:"#fde68a"}}>{c.addCurrency}</h3><div style={{display:"grid",gridTemplateColumns:"110px 1fr 100px",gap:8}}><input required maxLength={3} placeholder={c.code} value={currency.code} onChange={e=>setCurrency({...currency,code:e.target.value.toUpperCase()})} style={input}/><input required placeholder={c.name} value={currency.name} onChange={e=>setCurrency({...currency,name:e.target.value})} style={input}/><input placeholder={c.symbol} value={currency.symbol} onChange={e=>setCurrency({...currency,symbol:e.target.value})} style={input}/></div><button style={{...button,background:"#166534",color:"#dcfce7",marginTop:9}}><Plus size={16}/>{c.save}</button></form>
   <form onSubmit={addRate} style={{...card,padding:17}}><h3 style={{marginTop:0,color:"#86efac"}}>{c.setRate}</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8}}><select required value={rate.currency_code} onChange={e=>setRate({...rate,currency_code:e.target.value})} style={input}><option value="">{c.currency}</option>{currencies.filter(x=>!x.is_base).map(x=><option key={x.code} value={x.code}>{x.code} — {x.name}</option>)}</select><JalaliDateField value={rate.rate_date} onChange={(iso)=>setRate({...rate,rate_date:iso})} fa={language === "fa"} language={language} className="bg-[var(--erp-panel-solid)] text-[var(--erp-text)] border border-[var(--erp-border)] rounded-[11px] p-[10px_12px]"/><input required type="text" inputMode="numeric" placeholder={c.rate} value={language === "fa" ? toPersianDigits(rate.rate_to_base) : rate.rate_to_base} onChange={e=>setRate({...rate,rate_to_base:cleanNumberInput(e.target.value)})} style={input}/></div><button style={{...button,background:"#6d28d9",color:"#ede9fe",marginTop:9}}><TrendingUp size={16}/>{c.setRate}</button></form>
  </section>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:9,marginBottom:15}}>{currencies.map(x=><div key={x.code} style={{...card,padding:14}}><strong style={{color:x.is_base?"#86efac":"#fde68a",fontSize:19}}>{x.code} {x.symbol}</strong><div style={{color:"var(--erp-muted)",marginTop:5}}>{x.name}</div><div style={{marginTop:7}}>{c.latest}: {n(x.latest_rate)}</div><small style={{color:"var(--erp-muted)"}}>{x.latest_rate_date?date(x.latest_rate_date):"—"}</small></div>)}</section>
  {data&&<div style={{...card,padding:15,marginBottom:12,display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><span>{c.carrying}: <b>{money(data.total_carrying_value)}</b></span><span>{c.current}: <b>{money(data.total_current_value)}</b></span><span style={{color:data.total_unrealized_difference<0?"#fda4af":"#86efac"}}>{c.total}: <b>{money(data.total_unrealized_difference)}</b></span></div>}
  <section style={{...card,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:850}}><thead><tr>{[c.currency,c.account,c.foreign,c.carrying,c.latest,c.current,c.difference].map(x=><th key={x} style={{padding:12,textAlign:"start",color:"var(--erp-accent)"}}>{x}</th>)}</tr></thead><tbody>{!data?.items.length&&<tr><td colSpan={7} style={{padding:25,textAlign:"center",color:"var(--erp-muted)"}}>{c.no}</td></tr>}{data?.items.map(x=><tr key={x.currency_code+"-"+x.account_id}><td style={{padding:12,borderTop:"1px solid var(--erp-border)",fontWeight:900}}>{x.currency_code} {x.symbol}</td><td style={{padding:12}}>{x.account_code} — {x.account_name}</td><td style={{padding:12,color:"#fde68a"}}>{n(x.foreign_balance)} {x.currency_code}</td><td style={{padding:12}}>{money(x.base_balance)}</td><td style={{padding:12}}>{n(x.current_rate)}<div style={{fontSize:12,color:"var(--erp-muted)"}}>{date(x.rate_date)}</div></td><td style={{padding:12,color:"#86efac"}}>{money(x.current_base_value)}</td><td style={{padding:12,color:x.unrealized_difference<0?"#fda4af":"#86efac",fontWeight:900}}>{money(x.unrealized_difference)}</td></tr>)}</tbody></table></section>
 </div>
}
