import { useEffect,useState } from "react";
import { Calculator,Landmark,Plus,RefreshCw,Trash2,Wrench } from "lucide-react";
import toast from "react-hot-toast";
import JalaliDateField from "../components/forms/JalaliDateField";
import { useLanguage } from "../localization/useLanguage";
import { toPersianDigits, cleanNumberInput } from "../localization/helpers";
import { createFixedAsset,deleteFixedAsset,getFixedAssets,runAssetDepreciation } from "../services/fixedAssetsApi";

export default function FixedAssets(){
 const {language,dir,money,date,n}=useLanguage();
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [through,setThrough]=useState(new Date().toISOString().slice(0,10));
 const empty={name:"",asset_code:"",category:"",purchase_date:new Date().toISOString().slice(0,10),acquisition_cost:"",salvage_value:0,useful_life_months:60,payment_method:"bank",serial_number:"",location:"",note:""};
 const [form,setForm]=useState(empty);
 const c={title:language==="fa"?"دارایی‌های ثابت و استهلاک":language==="ar"?"الأصول الثابتة والإهلاك":language==="tr"?"Duran Varlıklar ve Amortisman":"Fixed Assets & Depreciation",sub:language==="fa"?"ثبت بهای تمام‌شده، محاسبه استهلاک و ارزش دفتری با سند خودکار":language==="ar"?"تسجيل التكلفة الفعلية واحتساب الإهلاك والقيمة الدفترية مع قيد تلقائي":language==="tr"?"Maliyet kaydı, otomatik amortisman hesaplama ve defter değeri":"Track acquisition cost, automatic depreciation, and book value",
 add:language==="fa"?"ثبت دارایی":language==="ar"?"تسجيل أصل":language==="tr"?"Varlık Ekle":"Add asset",name:language==="fa"?"نام دارایی":language==="ar"?"اسم الأصل":language==="tr"?"Varlık Adı":"Asset name",code:language==="fa"?"کد دارایی":language==="ar"?"رمز الأصل":language==="tr"?"Varlık Kodu":"Asset code",category:language==="fa"?"دسته‌بندی":language==="ar"?"التصنيف":language==="tr"?"Kategori":"Category",purchase:language==="fa"?"تاریخ خرید":language==="ar"?"تاريخ الشراء":language==="tr"?"Satın Alma Tarihi":"Purchase date",cost:language==="fa"?"بهای تمام‌شده":language==="ar"?"التكلفة الفعلية":language==="tr"?"Edinme Maliyeti":"Acquisition cost",salvage:language==="fa"?"ارزش اسقاط":language==="ar"?"قيمة الخردة":language==="tr"?"Hurda Değeri":"Salvage value",life:language==="fa"?"عمر مفید (ماه)":language==="ar"?"العمر الإنتاجي (بالأشهر)":language==="tr"?"Faydalı Ömür (Ay)":"Useful life (months)",method:language==="fa"?"روش پرداخت":language==="ar"?"طريقة الدفع":language==="tr"?"Ödeme Yöntemi":"Payment method",serial:language==="fa"?"شماره سریال":language==="ar"?"الرقم التسلسلي":language==="tr"?"Seri Numarası":"Serial number",location:language==="fa"?"محل استقرار":language==="ar"?"الموقع":language==="tr"?"Konum":"Location",save:language==="fa"?"ذخیره و ثبت سند":language==="ar"?"حفظ وترحيل القيد":language==="tr"?"Kaydet ve Fişle":"Save & post",run:language==="fa"?"اجرای استهلاک تا تاریخ":language==="ar"?"تنفيذ الإهلاك حتى تاريخ":language==="tr"?"Amortismanı Şu Tarihe Kadar Çalıştır":"Run depreciation through",refresh:language==="fa"?"به‌روزرسانی":language==="ar"?"تحديث":language==="tr"?"Yenile":"Refresh",count:language==="fa"?"تعداد دارایی":language==="ar"?"عدد الأصول":language==="tr"?"Varlık Sayısı":"Assets",accumulated:language==="fa"?"استهلاک انباشته":language==="ar"?"مجمع الإهلاك":language==="tr"?"Birikmiş Amortisman":"Accumulated depreciation",book:language==="fa"?"ارزش دفتری":language==="ar"?"القيمة الدفترية":language==="tr"?"Defter Değeri":"Book value",monthly:language==="fa"?"استهلاک ماهانه":language==="ar"?"الإهلاك الشهري":language==="tr"?"Aylık Amortisman":"Monthly depreciation",recognized:language==="fa"?"ماه شناسایی‌شده":language==="ar"?"الأشهر المعترف بها":language==="tr"?"Tanınan Aylar":"Recognized months",status:language==="fa"?"وضعیت":language==="ar"?"الحالة":language==="tr"?"Durum":"Status",delete:language==="fa"?"حذف":language==="ar"?"حذف":language==="tr"?"Sil":"Delete",no:language==="fa"?"دارایی ثابتی ثبت نشده است.":language==="ar"?"لا توجد أصول ثابتة مسجلة.":language==="tr"?"Kayıtlı duran varlık yok.":"No fixed assets registered.",bank:language==="fa"?"بانک":language==="ar"?"بنك":language==="tr"?"Banka":"Bank",cash:language==="fa"?"صندوق":language==="ar"?"نقدًا":language==="tr"?"Nakit":"Cash"};
 async function load(){setLoading(true);setError("");try{setData(await getFixedAssets())}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{
  const timer = setTimeout(() => { void load(); }, 0);
  return () => clearTimeout(timer);
 },[language]);
 async function submit(e){e.preventDefault();try{await createFixedAsset({...form,acquisition_cost:Number(form.acquisition_cost),salvage_value:Number(form.salvage_value),useful_life_months:Number(form.useful_life_months)});setForm(empty);toast.success(c.save);await load()}catch(e){toast.error(e.message)}}
 async function run(){try{const r=await runAssetDepreciation({through_date:through});toast.success(`${r.posted_count} — ${money(r.total_depreciation)}`);await load()}catch(e){toast.error(e.message)}}
 async function remove(id){try{await deleteFixedAsset(id);await load()}catch(e){toast.error(e.message)}}
 const card={background:"var(--erp-panel)",border:"1px solid var(--erp-border)",borderRadius:22,boxShadow:"0 18px 55px rgba(2,6,23,.3)"},input={background:"var(--erp-panel-solid)",color:"var(--erp-text)",border:"1px solid var(--erp-border)",borderRadius:11,padding:"10px 12px",minWidth:0},button={border:0,borderRadius:11,padding:"10px 13px",fontWeight:900,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:6};
 return <div dir={dir} style={{color:"var(--erp-text)",maxWidth:1500,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap",alignItems:"center",marginBottom:20}}><div style={{display:"flex",gap:13,alignItems:"center"}}><div style={{width:55,height:55,borderRadius:17,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#8b5cf6,#06b6d4)"}}><Landmark size={30}/></div><div><h1 className="text-violet-300" style={{margin:0,fontSize:"clamp(28px,4vw,40px)"}}>{c.title}</h1><p style={{margin:"6px 0 0",color:"var(--erp-muted)"}}>{c.sub}</p></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><JalaliDateField value={through} onChange={setThrough} fa={language === "fa"} language={language} className="bg-[var(--erp-panel-solid)] text-[var(--erp-text)] border border-[var(--erp-border)] rounded-[11px] p-[10px_12px]"/><button onClick={run} style={{...button,background:"#6d28d9",color:"#ede9fe"}}><Calculator size={16}/>{c.run}</button><button onClick={load} style={{...button,background:"var(--erp-panel-solid)",color:"var(--erp-accent)"}}><RefreshCw size={16}/>{loading?"...":c.refresh}</button></div></header>
  {error&&<div className="text-red-200" style={{...card,padding:15,marginBottom:15}}>{error}</div>}
  {data&&<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:15}}>{[[c.count,n(data.summary.asset_count),"var(--erp-accent)"],[c.cost,money(data.summary.acquisition_cost),null,"text-violet-300"],[c.accumulated,money(data.summary.accumulated_depreciation),"#fbbf24"],[c.book,money(data.summary.book_value),null,"text-green-300"]].map(([l,v,color,cls])=><div key={l} style={{...card,padding:16}}><div style={{color:"var(--erp-muted)"}}>{l}</div><strong className={cls} style={{display:"block",fontSize:21,marginTop:6,...(cls?null:{color})}}>{v}</strong></div>)}</section>}
  <form onSubmit={submit} style={{...card,padding:17,marginBottom:15}}><h3 style={{marginTop:0,color:"var(--erp-accent)"}}><Plus size={18} style={{display:"inline",marginInlineEnd:7}}/>{c.add}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:8}}><input required placeholder={c.name} value={form.name} onChange={e=>setForm({...form,name:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input required placeholder={c.code} value={form.asset_code} onChange={e=>setForm({...form,asset_code:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input placeholder={c.category} value={form.category} onChange={e=>setForm({...form,category:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><JalaliDateField value={form.purchase_date} onChange={(iso)=>setForm({...form,purchase_date:iso})} fa={language === "fa"} language={language} placeholder={c.purchase} className="bg-[var(--erp-panel-solid)] text-[var(--erp-text)] border border-[var(--erp-border)] rounded-[11px] p-[10px_12px]"/><input required type="text" inputMode="numeric" placeholder={c.cost} value={language === "fa" ? toPersianDigits(form.acquisition_cost) : form.acquisition_cost} onChange={e=>setForm({...form,acquisition_cost:cleanNumberInput(e.target.value)})} style={input}/><input type="text" inputMode="numeric" placeholder={c.salvage} value={language === "fa" ? toPersianDigits(form.salvage_value) : form.salvage_value} onChange={e=>setForm({...form,salvage_value:cleanNumberInput(e.target.value)})} style={input}/><input required type="text" inputMode="numeric" placeholder={c.life} value={language === "fa" ? toPersianDigits(form.useful_life_months) : form.useful_life_months} onChange={e=>setForm({...form,useful_life_months:cleanNumberInput(e.target.value)})} style={input}/><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})} style={input}><option value="bank">{c.bank}</option><option value="cash">{c.cash}</option></select><input placeholder={c.serial} value={form.serial_number} onChange={e=>setForm({...form,serial_number:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/><input placeholder={c.location} value={form.location} onChange={e=>setForm({...form,location:language==="fa"?toPersianDigits(e.target.value):e.target.value})} style={input}/></div><button style={{...button,background:"#166534",color:"#dcfce7",marginTop:10}}><Plus size={16}/>{c.save}</button></form>
  <section style={{...card,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:950}}><thead><tr>{[c.code,c.name,c.purchase,c.cost,c.accumulated,c.book,c.monthly,c.recognized,c.status,""].map(x=><th key={x} style={{padding:12,textAlign:"start",color:"var(--erp-accent)"}}>{x}</th>)}</tr></thead><tbody>{!data?.items.length&&<tr><td colSpan={10} style={{padding:25,textAlign:"center",color:"var(--erp-muted)"}}>{c.no}</td></tr>}{data?.items.map(a=><tr key={a.id}><td style={{padding:12,borderTop:"1px solid var(--erp-border)",fontWeight:900}}>{language==="fa"?toPersianDigits(a.asset_code):a.asset_code}</td><td style={{padding:12,borderTop:"1px solid var(--erp-border)"}}>{a.name}<div style={{color:"var(--erp-muted)",fontSize:12}}>{a.category} {a.location}</div></td><td style={{padding:12}}>{date(a.purchase_date)}</td>{[a.acquisition_cost,a.accumulated_depreciation,a.book_value,a.monthly_depreciation].map((v,i)=><td key={i} className={i===2?"text-green-300":undefined} style={{padding:12,fontWeight:i===2?900:500}}>{money(v)}</td>)}<td style={{padding:12}}>{n(a.recognized_months)}/{n(a.useful_life_months)}</td><td style={{padding:12,color:a.fully_depreciated?"#fbbf24":"#86efac"}}><Wrench size={15} style={{display:"inline"}}/> {a.status}</td><td style={{padding:12}}><button onClick={()=>remove(a.id)} style={{...button,background:"#7f1d1d",color:"#fee2e2"}}><Trash2 size={15}/></button></td></tr>)}</tbody></table></section>
 </div>
}
