import { useEffect,useState } from "react";
import { Calculator,Landmark,Plus,RefreshCw,Trash2,Wrench } from "lucide-react";
import toast from "react-hot-toast";
import { useLanguage } from "../localization/LanguageContext";
import { createFixedAsset,deleteFixedAsset,getFixedAssets,runAssetDepreciation } from "../services/fixedAssetsApi";

export default function FixedAssets(){
 const {language,dir,money,date,n}=useLanguage(),fa=language==="fa";
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [through,setThrough]=useState(new Date().toISOString().slice(0,10));
 const empty={name:"",asset_code:"",category:"",purchase_date:new Date().toISOString().slice(0,10),acquisition_cost:"",salvage_value:0,useful_life_months:60,payment_method:"bank",serial_number:"",location:"",note:""};
 const [form,setForm]=useState(empty);
 const c={title:fa?"دارایی‌های ثابت و استهلاک":"Fixed Assets & Depreciation",sub:fa?"ثبت بهای تمام‌شده، محاسبه استهلاک و ارزش دفتری با سند خودکار":"Track acquisition cost, automatic depreciation, and book value",
 add:fa?"ثبت دارایی":"Add asset",name:fa?"نام دارایی":"Asset name",code:fa?"کد دارایی":"Asset code",category:fa?"دسته‌بندی":"Category",purchase:fa?"تاریخ خرید":"Purchase date",cost:fa?"بهای تمام‌شده":"Acquisition cost",salvage:fa?"ارزش اسقاط":"Salvage value",life:fa?"عمر مفید (ماه)":"Useful life (months)",method:fa?"روش پرداخت":"Payment method",serial:fa?"شماره سریال":"Serial number",location:fa?"محل استقرار":"Location",save:fa?"ذخیره و ثبت سند":"Save & post",run:fa?"اجرای استهلاک تا تاریخ":"Run depreciation through",refresh:fa?"به‌روزرسانی":"Refresh",count:fa?"تعداد دارایی":"Assets",accumulated:fa?"استهلاک انباشته":"Accumulated depreciation",book:fa?"ارزش دفتری":"Book value",monthly:fa?"استهلاک ماهانه":"Monthly depreciation",recognized:fa?"ماه شناسایی‌شده":"Recognized months",status:fa?"وضعیت":"Status",delete:fa?"حذف":"Delete",no:fa?"دارایی ثابتی ثبت نشده است.":"No fixed assets registered.",bank:fa?"بانک":"Bank",cash:fa?"صندوق":"Cash"};
 async function load(){setLoading(true);setError("");try{setData(await getFixedAssets())}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[language]);
 async function submit(e){e.preventDefault();try{await createFixedAsset({...form,acquisition_cost:Number(form.acquisition_cost),salvage_value:Number(form.salvage_value),useful_life_months:Number(form.useful_life_months)});setForm(empty);toast.success(c.save);await load()}catch(e){toast.error(e.message)}}
 async function run(){try{const r=await runAssetDepreciation({through_date:through});toast.success(`${r.posted_count} — ${money(r.total_depreciation)}`);await load()}catch(e){toast.error(e.message)}}
 async function remove(id){try{await deleteFixedAsset(id);await load()}catch(e){toast.error(e.message)}}
 const card={background:"linear-gradient(145deg,rgba(15,23,42,.96),rgba(15,23,42,.74))",border:"1px solid rgba(34,211,238,.2)",borderRadius:22,boxShadow:"0 18px 55px rgba(2,6,23,.3)"},input={background:"#1e293b",color:"white",border:"1px solid #334155",borderRadius:11,padding:"10px 12px",minWidth:0},button={border:0,borderRadius:11,padding:"10px 13px",fontWeight:900,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:6};
 return <div dir={dir} style={{color:"#f8fafc",maxWidth:1500,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap",alignItems:"center",marginBottom:20}}><div style={{display:"flex",gap:13,alignItems:"center"}}><div style={{width:55,height:55,borderRadius:17,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#8b5cf6,#06b6d4)"}}><Landmark size={30}/></div><div><h1 style={{margin:0,color:"#c4b5fd",fontSize:"clamp(28px,4vw,40px)"}}>{c.title}</h1><p style={{margin:"6px 0 0",color:"#94a3b8"}}>{c.sub}</p></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input type="date" value={through} onChange={e=>setThrough(e.target.value)} style={input}/><button onClick={run} style={{...button,background:"#6d28d9",color:"#ede9fe"}}><Calculator size={16}/>{c.run}</button><button onClick={load} style={{...button,background:"#164e63",color:"#cffafe"}}><RefreshCw size={16}/>{loading?"...":c.refresh}</button></div></header>
  {error&&<div style={{...card,padding:15,color:"#fecaca",marginBottom:15}}>{error}</div>}
  {data&&<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:15}}>{[[c.count,n(data.summary.asset_count),"#67e8f9"],[c.cost,money(data.summary.acquisition_cost),"#c4b5fd"],[c.accumulated,money(data.summary.accumulated_depreciation),"#fbbf24"],[c.book,money(data.summary.book_value),"#86efac"]].map(([l,v,color])=><div key={l} style={{...card,padding:16}}><div style={{color:"#94a3b8"}}>{l}</div><strong style={{display:"block",color,fontSize:21,marginTop:6}}>{v}</strong></div>)}</section>}
  <form onSubmit={submit} style={{...card,padding:17,marginBottom:15}}><h3 style={{marginTop:0,color:"#67e8f9"}}><Plus size={18} style={{display:"inline",marginInlineEnd:7}}/>{c.add}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:8}}><input required placeholder={c.name} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} style={input}/><input required placeholder={c.code} value={form.asset_code} onChange={e=>setForm({...form,asset_code:e.target.value})} style={input}/><input placeholder={c.category} value={form.category} onChange={e=>setForm({...form,category:e.target.value})} style={input}/><input required type="date" title={c.purchase} value={form.purchase_date} onChange={e=>setForm({...form,purchase_date:e.target.value})} style={input}/><input required type="number" min="0.01" step="0.01" placeholder={c.cost} value={form.acquisition_cost} onChange={e=>setForm({...form,acquisition_cost:e.target.value})} style={input}/><input type="number" min="0" step="0.01" placeholder={c.salvage} value={form.salvage_value} onChange={e=>setForm({...form,salvage_value:e.target.value})} style={input}/><input required type="number" min="1" max="1200" placeholder={c.life} value={form.useful_life_months} onChange={e=>setForm({...form,useful_life_months:e.target.value})} style={input}/><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})} style={input}><option value="bank">{c.bank}</option><option value="cash">{c.cash}</option></select><input placeholder={c.serial} value={form.serial_number} onChange={e=>setForm({...form,serial_number:e.target.value})} style={input}/><input placeholder={c.location} value={form.location} onChange={e=>setForm({...form,location:e.target.value})} style={input}/></div><button style={{...button,background:"#166534",color:"#dcfce7",marginTop:10}}><Plus size={16}/>{c.save}</button></form>
  <section style={{...card,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:950}}><thead><tr>{[c.code,c.name,c.purchase,c.cost,c.accumulated,c.book,c.monthly,c.recognized,c.status,""].map(x=><th key={x} style={{padding:12,textAlign:"start",color:"#67e8f9"}}>{x}</th>)}</tr></thead><tbody>{!data?.items.length&&<tr><td colSpan={10} style={{padding:25,textAlign:"center",color:"#64748b"}}>{c.no}</td></tr>}{data?.items.map(a=><tr key={a.id}><td style={{padding:12,borderTop:"1px solid rgba(148,163,184,.1)",fontWeight:900}}>{a.asset_code}</td><td style={{padding:12,borderTop:"1px solid rgba(148,163,184,.1)"}}>{a.name}<div style={{color:"#64748b",fontSize:12}}>{a.category} {a.location}</div></td><td style={{padding:12}}>{date(a.purchase_date)}</td>{[a.acquisition_cost,a.accumulated_depreciation,a.book_value,a.monthly_depreciation].map((v,i)=><td key={i} style={{padding:12,color:i===2?"#86efac":"inherit",fontWeight:i===2?900:500}}>{money(v)}</td>)}<td style={{padding:12}}>{n(a.recognized_months)}/{n(a.useful_life_months)}</td><td style={{padding:12,color:a.fully_depreciated?"#fbbf24":"#86efac"}}><Wrench size={15} style={{display:"inline"}}/> {a.status}</td><td style={{padding:12}}><button onClick={()=>remove(a.id)} style={{...button,background:"#7f1d1d",color:"#fee2e2"}}><Trash2 size={15}/></button></td></tr>)}</tbody></table></section>
 </div>
}
