import { useEffect,useState } from "react";
import { AlertTriangle,Banknote,CheckCircle2,Clock3,Plus,RefreshCw,RotateCcw,Trash2,WalletCards,XCircle } from "lucide-react";
import toast from "react-hot-toast";
import { useLanguage } from "../localization/LanguageContext";
import { API_URL,getAuthHeaders } from "../services/api";
import { createCheque,deleteCheque,getCheques,transitionCheque } from "../services/treasuryApi";

export default function TreasuryCheques(){
 const {language,dir,money,date,n}=useLanguage(),fa=language==="fa",today=new Date().toISOString().slice(0,10);
 const [customers,setCustomers]=useState([]),[data,setData]=useState(null),[direction,setDirection]=useState("all"),[status,setStatus]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const empty={direction:"received",customer_id:"",amount:"",cheque_number:"",bank_name:"",branch_name:"",issue_date:today,due_date:today,note:""};
 const [form,setForm]=useState(empty);
 const c={title:fa?"خزانه‌داری و مدیریت چک‌ها":"Treasury & Cheques",sub:fa?"کنترل چک‌های دریافتی و پرداختی، سررسید، وصول و برگشت با سند خودکار":"Received and payable cheque lifecycle with due alerts and automatic vouchers",add:fa?"ثبت چک":"Add cheque",received:fa?"دریافتی":"Received",payable:fa?"پرداختی":"Payable",party:fa?"طرف‌حساب":"Party",amount:fa?"مبلغ":"Amount",number:fa?"شماره چک":"Cheque number",bank:fa?"بانک":"Bank",branch:fa?"شعبه":"Branch",issue:fa?"تاریخ صدور/دریافت":"Issue date",due:fa?"سررسید":"Due date",note:fa?"یادداشت":"Note",save:fa?"ثبت و صدور سند":"Save & post",all:fa?"همه":"All",pending:fa?"در جریان":"Pending",cleared:fa?"وصول‌شده":"Cleared",bounced:fa?"برگشتی":"Bounced",cancelled:fa?"باطل‌شده":"Cancelled",refresh:fa?"به‌روزرسانی":"Refresh",pendingReceived:fa?"دریافتی در جریان":"Pending received",pendingPayable:fa?"پرداختی در جریان":"Pending payable",overdue:fa?"سررسیدگذشته":"Overdue",dueSoon:fa?"نزدیک سررسید":"Due soon",actions:fa?"عملیات":"Actions",clear:fa?"وصول":"Clear",bounce:fa?"برگشت":"Bounce",cancel:fa?"ابطال":"Cancel",delete:fa?"حذف":"Delete",none:fa?"چکی ثبت نشده است.":"No cheques registered.",days:fa?"روز":"days"};
 async function load(){setLoading(true);setError("");try{const [r,cs]=await Promise.all([getCheques(direction,status),fetch(`${API_URL}/customers`,{headers:getAuthHeaders()}).then(x=>x.json())]);setData(r);setCustomers(Array.isArray(cs)?cs:[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[language]);
 async function submit(e){e.preventDefault();try{await createCheque({...form,customer_id:Number(form.customer_id),amount:Number(form.amount)});setForm(empty);await load()}catch(e){toast.error(e.message)}}
 async function move(id,next){try{await transitionCheque(id,{status:next,event_date:today,note:""});await load()}catch(e){toast.error(e.message)}}
 async function remove(id){try{await deleteCheque(id);await load()}catch(e){toast.error(e.message)}}
 const card={background:"linear-gradient(145deg,rgba(15,23,42,.96),rgba(15,23,42,.74))",border:"1px solid rgba(34,211,238,.2)",borderRadius:22,boxShadow:"0 18px 55px rgba(2,6,23,.3)"},input={background:"#1e293b",color:"white",border:"1px solid #334155",borderRadius:11,padding:"10px 12px",minWidth:0},button={border:0,borderRadius:11,padding:"9px 12px",fontWeight:900,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:5};
 return <div dir={dir} style={{color:"#f8fafc",maxWidth:1500,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap",alignItems:"center",marginBottom:20}}><div style={{display:"flex",gap:13,alignItems:"center"}}><div style={{width:55,height:55,borderRadius:17,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#06b6d4,#2563eb)"}}><WalletCards size={30}/></div><div><h1 style={{margin:0,color:"#a5f3fc",fontSize:"clamp(28px,4vw,40px)"}}>{c.title}</h1><p style={{margin:"6px 0 0",color:"#94a3b8"}}>{c.sub}</p></div></div><div style={{display:"flex",gap:7}}><select value={direction} onChange={e=>setDirection(e.target.value)} style={input}><option value="all">{c.all}</option><option value="received">{c.received}</option><option value="payable">{c.payable}</option></select><select value={status} onChange={e=>setStatus(e.target.value)} style={input}><option value="all">{c.all}</option><option value="pending">{c.pending}</option><option value="cleared">{c.cleared}</option><option value="bounced">{c.bounced}</option><option value="cancelled">{c.cancelled}</option></select><button onClick={load} style={{...button,background:"#164e63",color:"#cffafe"}}><RefreshCw size={16}/>{loading?"...":c.refresh}</button></div></header>
  {error&&<div style={{...card,padding:15,color:"#fecaca",marginBottom:15}}>{error}</div>}
  {data&&<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10,marginBottom:15}}>{[[c.pendingReceived,money(data.summary.received_pending),Banknote,"#86efac"],[c.pendingPayable,money(data.summary.payable_pending),WalletCards,"#fda4af"],[c.overdue,n(data.summary.overdue_count),AlertTriangle,"#fbbf24"],[c.dueSoon,n(data.summary.due_soon_count),Clock3,"#67e8f9"]].map(([l,v,I,color])=><div key={l} style={{...card,padding:16}}><I size={19} color={color}/><div style={{color:"#94a3b8",marginTop:7}}>{l}</div><strong style={{display:"block",color,fontSize:21,marginTop:5}}>{v}</strong></div>)}</section>}
  <form onSubmit={submit} style={{...card,padding:17,marginBottom:15}}><h3 style={{marginTop:0,color:"#67e8f9"}}><Plus size={18} style={{display:"inline",marginInlineEnd:7}}/>{c.add}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(155px,1fr))",gap:8}}><select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})} style={input}><option value="received">{c.received}</option><option value="payable">{c.payable}</option></select><select required value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} style={input}><option value="">{c.party}</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required type="number" min="0.01" step="0.01" placeholder={c.amount} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} style={input}/><input required placeholder={c.number} value={form.cheque_number} onChange={e=>setForm({...form,cheque_number:e.target.value})} style={input}/><input placeholder={c.bank} value={form.bank_name} onChange={e=>setForm({...form,bank_name:e.target.value})} style={input}/><input placeholder={c.branch} value={form.branch_name} onChange={e=>setForm({...form,branch_name:e.target.value})} style={input}/><input required type="date" title={c.issue} value={form.issue_date} onChange={e=>setForm({...form,issue_date:e.target.value})} style={input}/><input required type="date" title={c.due} value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} style={input}/></div><button style={{...button,background:"#166534",color:"#dcfce7",marginTop:10}}><Plus size={16}/>{c.save}</button></form>
  <section style={{...card,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1000}}><thead><tr>{[c.number,c.received+"/"+c.payable,c.party,c.bank,c.due,c.amount,c.status,c.actions].map(x=><th key={x} style={{padding:12,textAlign:"start",color:"#67e8f9"}}>{x}</th>)}</tr></thead><tbody>{!data?.items.length&&<tr><td colSpan={8} style={{padding:25,textAlign:"center",color:"#64748b"}}>{c.none}</td></tr>}{data?.items.map(x=><tr key={x.id}><td style={{padding:12,borderTop:"1px solid rgba(148,163,184,.1)",fontWeight:900}}>{x.cheque_number}</td><td style={{padding:12,color:x.direction==="received"?"#86efac":"#fda4af"}}>{c[x.direction]}</td><td style={{padding:12}}>{x.customer_name}</td><td style={{padding:12}}>{x.bank_name||"—"}<div style={{fontSize:12,color:"#64748b"}}>{x.branch_name}</div></td><td style={{padding:12,color:x.overdue?"#fbbf24":"inherit"}}>{date(x.due_date)}<div style={{fontSize:12}}>{n(x.days_to_due)} {c.days}</div></td><td style={{padding:12,fontWeight:900}}>{money(x.amount)}</td><td style={{padding:12,color:x.status==="pending"?"#fbbf24":x.status==="cleared"?"#86efac":"#fda4af"}}>{c[x.status]}</td><td style={{padding:12,whiteSpace:"nowrap"}}>{x.status==="pending"&&<><button onClick={()=>move(x.id,"cleared")} style={{...button,background:"#166534",color:"#dcfce7"}}><CheckCircle2 size={14}/>{c.clear}</button> {x.direction==="received"&&<button onClick={()=>move(x.id,"bounced")} style={{...button,background:"#7f1d1d",color:"#fee2e2"}}><RotateCcw size={14}/>{c.bounce}</button>} <button onClick={()=>move(x.id,"cancelled")} style={{...button,background:"#78350f",color:"#fef3c7"}}><XCircle size={14}/>{c.cancel}</button> <button onClick={()=>remove(x.id)} style={{...button,background:"#334155",color:"#e2e8f0"}}><Trash2 size={14}/></button></>}</td></tr>)}</tbody></table></section>
 </div>
}
