import { useEffect, useState } from "react";

import { useAuth } from "../../auth/AuthContext";
import { useLanguage } from "../../localization/useLanguage";
import { getSettings } from "../../services/api";

// Standard report header (Task 02 Section 9): company logo/name, report
// title, period, generated date/time, generated by, and an optional
// filter summary - shared across print/export-capable report pages so
// none of them hand-roll their own branded header again. Prints on paper
// (unlike each page's own "no-print" controls bar) because it carries no
// interactive controls, only the report's identity.
export default function ReportHeader({ title, subtitle, period, filterSummary }) {
  const { user } = useAuth();
  const { dir, language, time } = useLanguage();
  const tr = (fa, ar, trText, en) => (language === "fa" ? fa : language === "ar" ? ar : language === "tr" ? trText : en);

  // No legacy brand-name fallback - the report title below already
  // establishes application context, so an unconfigured/loading company
  // name simply renders nothing rather than a placeholder brand string.
  const [branding, setBranding] = useState({ company_name: "", logo_data: "", show_logo: true });

  useEffect(() => {
    const timer = setTimeout(() => {
      getSettings().then((data) => setBranding({
        company_name: data.company_name || "",
        logo_data: data.logo_data || "",
        show_logo: data.show_logo !== false,
      })).catch(() => {});
    }, 0);
    return () => clearTimeout(timer);
  }, []);

  return (
    <header dir={dir} className="erp-report-header" style={{ marginBottom: 18, paddingBottom: 14, borderBottom: "2px solid var(--erp-border)" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 14, flexWrap: "wrap" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          {branding.show_logo && branding.logo_data && (
            <img src={`data:image/png;base64,${branding.logo_data}`} alt="" style={{ height: 42, width: "auto" }} />
          )}
          {branding.company_name && (
            <div style={{ fontWeight: 900, fontSize: 16, color: "var(--erp-text)" }}>{branding.company_name}</div>
          )}
        </div>
        <div style={{ textAlign: dir === "rtl" ? "left" : "right", fontSize: 12, color: "var(--erp-muted)" }}>
          <div>{tr("تولید شده در: ", "أُنشئ في: ", "Oluşturma: ", "Generated: ")}{time(new Date())}</div>
          {user?.full_name && <div>{tr("تهیه‌کننده: ", "أعده: ", "Hazırlayan: ", "Generated by: ")}{user.full_name}</div>}
        </div>
      </div>
      <h1 style={{ margin: "14px 0 4px", fontSize: "clamp(22px,3vw,30px)", color: "var(--erp-text)" }}>{title}</h1>
      {subtitle && <p style={{ margin: 0, color: "var(--erp-muted)" }}>{subtitle}</p>}
      {(period || filterSummary) && (
        <div style={{ marginTop: 8, fontSize: 13, color: "var(--erp-muted)" }}>
          {period && <span>{tr("بازه: ", "الفترة: ", "Dönem: ", "Period: ")}{period}</span>}
          {period && filterSummary && <span> · </span>}
          {filterSummary && <span>{filterSummary}</span>}
        </div>
      )}
    </header>
  );
}
